---
name: "NFO Chapters"
guid: "BE72D436-AB23-44B4-8625-9A8F3892D27A"
imageUrl: "https://github.com/Viperinius/jellyfin-plugin-nfo-chapters/raw/master/viperinius-plugin-nfochapters.png"
version: "1.0.0.0"
targetAbi: "10.8.4.0"
framework: "net6.0"
overview: "This plugin enables the use of chapter tags in NFOs"
description: >
  This plugin extends the NFO parser for your Movies.
  You can specify your own chapters in the NFO which will get picked up by the plugin during a library scan.
category: "Metadata"
owner: "Viperinius"
artifacts:
- "Viperinius.Plugin.NfoChapters.dll"
changelog: >
  changelog
